### ISSUE TITLE
PDF reader

### ISSUE THREAD

**Issue by hasanmdarif** [hasanmdarif/Python_Programs#1]
Create a python program in which your computer will speak the pdf.

**Comment by abhinavanand123** [comment]
I want to work on it @hasanmdarif 
can you plz explain a bit of your requirements.

**Comment by hasanmdarif** [comment]
> I want to work on it @hasanmdarif
> can you plz explain a bit of your requirements.

Hii Abhinav, You have to write some code that make your computer speak. Take any pdf and write a bit of code that help you to lay down and hear to the pdf rather than reading it. Hope you get the point. You can take reference from my code.

**Comment by abhinavanand123** [comment]
Awesome! I got you.
Can you plz assign me this work I am ready to work on it.

**Comment by hasanmdarif** [comment]
> Awesome! I got you.
> Can you plz assign me this work I am ready to work on it.

Sure

**Comment by abhinavanand123** [comment]
Could you please add the topic as hactoberfest as I am a part of it

**Comment by hasanmdarif** [comment]
I have added the topic

**Comment by abhinavanand123** [comment]
I have created the pull request

**Comment by hasanmdarif** [comment]
@abhinavanand123 I'm not getting any pr. Please check again
