### ISSUE TITLE
Qr converter

### ISSUE THREAD

**Issue by hasanmdarif** [hasanmdarif/Python_Programs#2]
Write a python program to convert text into QR code

**Comment by BhuvaneshPatil** [comment]
I would like to contribute on this issue.
@hasanmdarif

**Comment by hasanmdarif** [comment]
> I would like to contribute on this issue.
> @hasanmdarif

Sure, go ahead

**Comment by mridul-io** [comment]
Apparently, your repo doesn't have Hacktoberfest added as a topic and thus it is showing ineligible for the contest. Can you add Hacktoberfest as a topic so it becomes eligible

**Comment by hasanmdarif** [comment]
> Apparently, your repo doesn't have Hacktoberfest added as a topic and thus it is showing ineligible for the contest. Can you add Hacktoberfest as a topic so it becomes eligible

Thanks buddy!

**Comment by rodneyosodo** [comment]
This issue should be closed as it has already been fixed
