### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by hasanmdarif** [hasanmdarif/Python_Programs#24]

**Comment by iwtga** [comment]
hey @hasanmdarif! how do add the 'hacktoberfest-accepted' label to pull requests? I have done 2 PRs which got merged. But they don't have the hacktoberfest-accepted label.

Coming to the issue, i'll update the readme file in a few minutes:) 

And Thanks for creating the repository! I practiced my git skills and learnt some best practices, do's and don'ts!

**Comment by iwtga** [comment]
Created a Pull Request with the Updated Readme:)
Do Check it;)

**Comment by hasanmdarif** [comment]
Hey @iwtga my repo topic is set to hacktoberfest, so your pr will be counted toward hacktoberfest.

**Comment by iwtga** [comment]
okay! thanks @hasanmdarif!
👍
